server:
  port: 8280
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: issue-service
http:
  logging:
    enabled: true
    log-body: true
    log-level: warn
timing:
  enabled: true
  log-body: true
  log-level: warn